### ISSUE TITLE
Issue upgrading.

### ISSUE THREAD

**Issue by bhupen** [hybridgroup/homebrew-tools#3]
Encountering this issue when upgrading homebrew on MacOS 10.13.6.

Error: Calling MacOS.prefer_64_bit? is disabled! There is no replacement.
Please report this to the hybridgroup/tools tap:
  /usr/local/Homebrew/Library/Taps/hybridgroup/homebrew-tools/gort.rb:6

**Comment by deadprogram** [comment]
Hello @bhupen I have just merged https://github.com/hybridgroup/homebrew-tools/pull/5 which corrects this issue. Now closing, please reopen if needed.
